/*
* This header is generated by classdump-dyld 1.0
* on Thursday, December 22, 2016 at 6:33:23 PM Eastern European Standard Time
* Operating System: Version 10.1.1 (Build 14B100)
* Image Source: /System/Library/CoreServices/SpringBoard.app/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol SBIconScrollViewDelegate <UIScrollViewDelegate>
@required
-(void)iconScrollViewDidCancelTouchTracking:(id)arg1;
-(void)iconScrollViewWillCancelTouchTracking:(id)arg1;

@end

